# Generated by Django 3.0.2 on 2020-01-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20200116_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdevice',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
