# Generated by Django 3.0.2 on 2020-01-16 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0003_auto_20200116_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='dweller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dwelled_houses', to=settings.AUTH_USER_MODEL),
        ),
    ]
