# Generated by Django 3.0.2 on 2020-01-16 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20200116_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.Room'),
        ),
    ]
