# Generated by Django 3.0.2 on 2020-02-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(default=20, max_length=2),
        ),
    ]
