# Generated by Django 3.0.2 on 2020-01-16 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 17, 21, 40, 450110)),
        ),
        migrations.AddField(
            model_name='report',
            name='saved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='wasted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='avg_consumption',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='generated',
            field=models.IntegerField(default=0),
        ),
    ]
