# Generated by Django 3.0.2 on 2020-02-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_auto_20200116_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='cmu_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
